import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CartProvider } from './context/CartProvider'
import { ProductsProvider } from './context/ProductsProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ProductsProvider>
      <CartProvider>
      <body className={inter.className}>{children}</body>
      </CartProvider>
      </ProductsProvider>
    </html>
  )
}
